apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ibmcloud-operators
  name: ibmcloud-operator
  namespace: ibm-service-binding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibmcloud-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ibmcloud-operator
    spec:
      imagePullSecrets:
      - name: ibm-cfn-system-us-icr-io
      containers:
      - args:
        - -logtostderr=true
        - -v=5
        env:
        - name: CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: (( concat environment.registry-path "/cloud-operators:" environment.versions.cloud-operators ))
        name: ibmcloud-operators
      serviceAccountName: ibmcloud-operator
